[openai]
key = "sk-0a9269c12ba04dd5ae7544649486d288"


[supabase]
url = "https://ntwzwunvwsjpvkzcftbj.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50d3p3dW52d3NqcHZremNmdGJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk5NDQ1NjYsImV4cCI6MjA5NTUyMDU2Nn0.p34yX4OrWNdFpX4XyccW6ONJSFmY9ZTWI6squxj-rPg"
